apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: kustomization

helmGlobals:
  chartHome: ../../helmCharts/


helmCharts:
- includeCRDs: true
  name: nginx-ingress
  repo: https://helm.nginx.com/stable
  version: 1.1.2
  releaseName: nginx-ingress
  namespace: nginx-ingress
  valuesFile: values.yaml


generatorOptions:
  disableNameSuffixHash: true