apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: kustomization

namespace: signer

helmCharts:
- name: signer
  version: 0.1.0
  repo: oci://ghcr.io/novog93/charts/
  releaseName: signer
  namespace: signer
  valuesFile: values.yaml


images:
- name: ghcr.io/novog93/signer
  newName: ghcr.io/novog93/signer
  newTag: "latest"