apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kind-dev-cluster
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-dev
    kind: ClusterSecretStore
  target:
    name: kind-dev-cluster
    deletionPolicy: Delete
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: cluster
      data:
        name: kind-dev
        server: "{{ .server }}"
        config: |
          {
            "bearerToken": "{{ .bearerToken }}",
            "tlsClientConfig": {
              "insecure": true
            }
          }
  data:
    - secretKey: server
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: argocd-clusters/kind-dev
        property: server
    - secretKey: bearerToken
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: argocd-clusters/kind-dev
        property: bearerToken
