apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: copy-wildcard-secret
spec:
  validationFailureAction: Enforce
  useServerSideApply: true # Ignore metadata changes
  rules:
  - name: copy-wildcard-secret
    skipBackgroundRequests: false
    match:
      any:
      - resources:
          kinds:
          - Namespace
    exclude:
      any:
      - resources:
          kinds: ["Namespace"]
          names:
          - "!wildcard-tls"
          - "!calico-apiserver"
          - "!calico-system"
          - "!cert-manager"
          - "!external-dns"
          - "!kube-node-lease"
          - "!kube-public"
          - "!kube-system"
          - "!kyverno"
          - "!metallb-system"
          - "!nfs-provisioner"
          - "!tigera-operator"
    generate:
      apiVersion: v1
      kind: Secret
      name: wildcard-tls
      namespace: "{{request.object.metadata.name}}"
      synchronize: true
      generateExisting: true
      clone:
        name: wildcard-tls
        namespace: wildcard-tls