apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: beans-and-bites-backend
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "beans-and-bites-backend.novotny.live"
  labels:
    funnel: "false"
spec:
  externalDNS:
    enable: true
  host: beans-and-bites-backend.novotny.live
  tls:
    secret: wildcard-tls
  upstreams:
  - name: beans-and-bites-backend
    service: backend-service
    port: 8000
  routes:
  - path: =/
    action:
      redirect:
        url: https://${host}/admin/
        code: 301
  - path: /
    action:
      pass: beans-and-bites-backend
