apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: kustomization

helmGlobals:
  chartHome: ../../helmCharts/
resources:
- virtualserver.yaml
- es-obsidian-couchdb.yaml

helmCharts:
- includeCRDs: true
  name: couchdb
  repo: https://apache.github.io/couchdb-helm
  version: 4.6.1
  releaseName: obsidian
  namespace: obsidian
  valuesFile: values.yaml

patches:
- target:
    kind: Job
    name: obsidian-post-install
  patch: |-
    - op: "replace"
      path: "/metadata/annotations"
      value:
        argocd.argoproj.io/hook: Sync
    - op: "add"
      path: "/spec/template/spec/tolerations"
      value:
        - key: apps
          operator: Exists
          effect: NoSchedule
    - op: "add"
      path: "/spec/template/spec/affinity"
      value:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: apps
                    operator: Exists


generatorOptions:
  disableNameSuffixHash: true