apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: kustomization

helmGlobals:
  chartHome: ../../helmCharts/


helmCharts:
- includeCRDs: true
  name: nfs-subdir-external-provisioner
  repo: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
  version: 4.0.18
  releaseName: nfs-provisioner
  namespace: nfs-provisioner
  valuesFile: values.yaml


generatorOptions:
  disableNameSuffixHash: true