global:
  domain: argocd.novotny.live
  tolerations:
    - key: "tools"
      operator: "Exists"
      effect: "NoSchedule"

  affinity:
    nodeAffinity:
      type: hard
      matchExpressions:
      - key: "tools"
        operator: "Exists"
  

configs:
  params:
    server.insecure: true

server:
  ingress:
    enabled: false

controller:
  resources:
    limits:
      cpu: 4000m
    requests:
      cpu: 250m
      memory: 256Mi