apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tailscale-auth-key
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-dev
    kind: ClusterSecretStore
  target:
    name: tailscale-auth-key
    deletionPolicy: Delete
  data:
    - secretKey: auth-key
      remoteRef:
        conversionStrategy: Default	
        decodingStrategy: None
        metadataPolicy: None
        key: tools/pihole/tailscale-auth-key
        property: auth-key
