apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: kustomization

helmGlobals:
  chartHome: ../../helmCharts-tools/

resources:
- virtualserver.yaml
- es-pihole-password.yaml
- es-tailscale-auth-key.yaml
- tailscale-sa.yaml
- tailscale-role.yaml
- tailscale-rolebinding.yaml

helmCharts:
- includeCRDs: true
  name: pihole
  repo: https://mojo2600.github.io/pihole-kubernetes/
  version: 2.31.0
  releaseName: pihole
  namespace: pihole
  valuesFile: values.yaml

patches:
- target:
    kind: Pod
    name: pihole-smoke-test
  path: smoke-test-patch.yaml
- target:
    kind: Deployment
    name: pihole
  patch: |-
    - op: add
      path: /spec/template/spec/serviceAccountName
      value: tailscale

generatorOptions:
  disableNameSuffixHash: true