apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: elena-reader-binding
  namespace: harbor
subjects:
- kind: User
  name: elena
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: reader
  apiGroup: rbac.authorization.k8s.io
