apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: elena-homelab-harbor-binding
  namespace: harbor
subjects:
- kind: User
  name: elena
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: homelab:harbor
  apiGroup: rbac.authorization.k8s.io
