# external-secrets/es-dev-app.yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-postgres-user
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-dev
    kind: ClusterSecretStore
  target:
    name: immich-postgres-user
    deletionPolicy: Delete
  data:
    - secretKey: DB_USERNAME
      remoteRef:
        conversionStrategy: Default	
        decodingStrategy: None
        metadataPolicy: None
        key: apps/immich/immich-postgres-user
        property: DB_USERNAME
    - secretKey: DB_DATABASE_NAME
      remoteRef:
        conversionStrategy: Default	
        decodingStrategy: None
        metadataPolicy: None
        key: apps/immich/immich-postgres-user
        property: DB_DATABASE_NAME
    - secretKey: DB_PASSWORD
      remoteRef:
        conversionStrategy: Default	
        decodingStrategy: None
        metadataPolicy: None
        key: apps/immich/immich-postgres-user
        property: DB_PASSWORD
    - secretKey: username
      remoteRef:
        conversionStrategy: Default	
        decodingStrategy: None
        metadataPolicy: None
        key: apps/immich/immich-postgres-user
        property: username
    - secretKey: password
      remoteRef:
        conversionStrategy: Default	
        decodingStrategy: None
        metadataPolicy: None
        key: apps/immich/immich-postgres-user
        property: password
