---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: immich-smb-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  volumeName: immich-smb
  storageClassName: smb