apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: immich
  annotations:
    # external-dns will read the host from .spec.host
    external-dns.alpha.kubernetes.io/hostname: "immich.novotny.live"
  labels:
    tailscale.com/funnel: "false"
spec:
  externalDNS:
    enable: true
  host: immich.novotny.live
  tls:
    secret: wildcard-tls
  upstreams:
  - name: immich
    service: immich-server
    port: 2283
  routes:
  - path: /
    action:
      pass: immich
