apiVersion: v1
kind: Pod
metadata:
  labels:
    run: netshoot
  name: netshoot
spec:
  tolerations:
    - key: apps
      operator: Exists
      effect: NoSchedule
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: apps
                operator: Exists
  containers:
  - command:
    - sleep
    - inf
    image: nicolaka/netshoot
    name: netshoot
    resizePolicy:
    - resourceName: cpu
      restartPolicy: NotRequired
    - resourceName: memory
      restartPolicy: NotRequired
    resources: 
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 200m
        memory: 400Mi
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
