apiVersion: v1
kind: Pod
metadata:
  labels:
    run: netshoot-client
  name: netshoot-client
spec:
  tolerations:
    - key: apps
      operator: Exists
      effect: NoSchedule
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: apps
                operator: Exists
  containers:
  - command:
    - sleep
    - inf
    image: nicolaka/netshoot
    name: netshoot-client
    resizePolicy:
    - resourceName: cpu
      restartPolicy: NotRequired
    - resourceName: memory
      restartPolicy: NotRequired
    resources: 
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 200m
        memory: 400Mi
    volumeMounts:
        - name: tls-certs
          mountPath: /var/run/secrets/tls
          readOnly: true
  volumes:
  - name: tls-certs
    projected:
      sources:
      - podCertificate:
          signerName: kubernetes.io/kubelet-serving # issuers.cert-manager.io/letsencrypt-dns-cloudflare
          keyType: rsa
          path: tls.crt
  dnsPolicy: ClusterFirst
  restartPolicy: Always
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: netshoot-server
  name: netshoot-server
spec:
  tolerations:
    - key: apps
      operator: Exists
      effect: NoSchedule
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: apps
                operator: Exists
  containers:
  - command:
    - sleep
    - inf
    image: nicolaka/netshoot
    name: netshoot-server
    resizePolicy:
    - resourceName: cpu
      restartPolicy: NotRequired
    - resourceName: memory
      restartPolicy: NotRequired
    resources: 
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 200m
        memory: 400Mi
    volumeMounts:
        - name: tls-certs
          mountPath: /var/run/secrets/tls
          readOnly: true
  volumes:
  - name: tls-certs
    projected:
      sources:
      - podCertificate:
          signerName: kubernetes.io/kubelet-serving # issuers.cert-manager.io/letsencrypt-dns-cloudflare
          keyType: rsa
          path: tls.crt
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
