apiVersion: v1
kind: Pod
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Validate=false
  labels:
    run: netshoot
  name: netshoot
spec:
  tolerations:
    - key: apps
      operator: Exists
      effect: NoSchedule
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: apps
                operator: Exists
  containers:
  - command:
    - sleep
    - inf
    image: nicolaka/netshoot
    name: netshoot
    resizePolicy:
    - resourceName: cpu
      restartPolicy: NotRequired
    - resourceName: memory
      restartPolicy: NotRequired
    resources: 
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 200m
        memory: 400Mi
    volumeMounts:
        - name: tls-certs
          mountPath: /var/run/secrets/tls
          readOnly: true
  volumes:
  - name: tls-certs
    projected:
      sources:
      - podCertificate:
          signerName: kubernetes.io/kubelet-serving
          keyType: RSA3072
          credentialBundlePath: tls.crt
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
