apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: kustomization

helmGlobals:
  chartHome: ../../helmCharts/


helmCharts:
- includeCRDs: true
  name: csi-driver-smb
  repo: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts
  version: v1.18.0
  releaseName: csi-driver-smb
  namespace: smb-provisioner
  valuesFile: values.yaml


generatorOptions:
  disableNameSuffixHash: true