global:
  tolerations:
    - key: "tools"
      operator: "Exists"
      effect: "NoSchedule"
  
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: "tools"
              operator: "Exists"

policyReportsCleanup:
  image:
    repository: registry.k8s.io/kubectl
    tags: v1.32.7