# yaml-language-server: $schema=../../helmCharts/vault-0.30.0/vault/values.schema.json


injector:
  affinity: |
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: "tools"
                operator: "Exists"
  
  tolerations:
    - key: "tools"
      operator: "Exists"
      effect: "NoSchedule"


server:
  # Ensure Vault runs with an SA and that it gets system:auth-delegator
  serviceAccount:
    create: true
    name: vault

  extraEnvironmentVars:
    VAULT_SKIP_VERIFY: "true"
    USERS: "Georg"
    USER_PASSWORD: "changeme"
    FORMAT: "" # -format=json
    ESO_NS: "external-secret-operator"

  postStart:
  - /bin/sh
  - -c
  - |
    chmod +x /tmp/init.sh || true
    nohup /tmp/init.sh > /tmp/keys/logs.txt 2>&1 &


  volumeMounts:
  - name: init-script
    mountPath: /tmp/init.sh
    subPath: init.sh
  - name: keys-json
    mountPath: /tmp/keys/
  - name: policies
    mountPath: /tmp/policies/


  volumes:
  - name: init-script
    configMap:
      name: vault-init-script
      defaultMode: 0755
  - name: policies
    configMap:
      name: policies
      defaultMode: 0555
  - name: keys-json
    persistentVolumeClaim:
      claimName: vault-keys-pvc

  affinity: |
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: "tools"
                operator: "Exists"

  tolerations:
    - key: "tools"
      operator: "Exists"
      effect: "NoSchedule"

  dataStorage:
    enabled: true
    size: 10Gi
    mountPath: "/vault/data"
    storageClass: nfs-client
    accessMode: ReadWriteOnce

# Vault UI
ui:
  enabled: true
