apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db-credentials
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: vault-dev
    kind: ClusterSecretStore
  target:
    name: db-credentials
    creationPolicy: Owner
  data:
  - secretKey: POSTGRES_DB
    remoteRef:
      key: apps/rcl/db-credentials
      property: POSTGRES_DB
  - secretKey: POSTGRES_USER
    remoteRef:
      key: apps/rcl/db-credentials
      property: POSTGRES_USER
  - secretKey: POSTGRES_PASSWORD
    remoteRef:
      key: apps/rcl/db-credentials
      property: POSTGRES_PASSWORD
  - secretKey: SECRET_KEY
    remoteRef:
      key: apps/rcl/db-credentials
      property: SECRET_KEY
  - secretKey: MTLS_ALLOWED_CLIENTS
    remoteRef:
      key: apps/rcl/db-credentials
      property: MTLS_ALLOWED_CLIENTS
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  POSTGRES_HOST: db-service
  POSTGRES_PORT: "5432"
  CORS_ALLOWED_ORIGINS: "http://localhost,http://localhost:3000,http://127.0.0.1,https://robotics-content-lab.novotny.live,https://robotics-content-lab-rcl.tail73aecd.ts.net,https://robotics-content-lab-gateway.novotny.live"
  ALLOWED_HOSTS: "localhost,127.0.0.1,robotics-content-lab.novotny.live,backend,backend-service,backend-service.rcl,backend-service.rcl.svc.cluster.local,robotics-content-lab-rcl.tail73aecd.ts.net,robotics-content-lab-gateway.novotny.live,rcl-api.novotny.live,robotics-content-lab-backend.novotny.live,robotics-content-lab-backend-rcl.tail73aecd.ts.net"
  RUN_SEED_DATA: "true"