apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: kustomization

namespace: rcl


resources:
- config.yaml
- virtualserver-frontend.yaml
- virtualserver-backend.yaml
- virtualserver-api.yaml
- httproute.yaml
- backend.yaml
- email-outbox-cronjob.yaml
- resource-migration-job.yaml
- frontend.yaml
- db.yaml
- registry-secret.yaml
- mtls-cert.yaml
- mtls-nginx-ca-secret.yaml
- mtls-policy.yaml


generatorOptions:
  disableNameSuffixHash: true

images:
- name: ghcr.io/robotics-content-lab/website/backend
  newTag: staging-20260720-851d209
- name: ghcr.io/robotics-content-lab/website/frontend
  newTag: staging-20260720-851d209

patches:
- target:
    kind: Deployment
  patch: |-
    - op: add
      path: /spec/template/spec/tolerations
      value: []
    - op: add
      path: /spec/template/spec/tolerations/-
      value:
        key: apps
        operator: Equal
        value: "true"
        effect: NoSchedule
- target:
    kind: Deployment
  patch: |-
    - op: add
      path: /spec/template/spec/affinity
      value:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: apps
                    operator: Exists
- target:
    kind: Deployment
  patch: |-
    - op: add
      path: /spec/template/spec/imagePullSecrets
      value:
        - name: ghcr-registry
