apiVersion: v1
kind: Secret
metadata:
  name: mtls-nginx-ca-secret
type: nginx.org/ca
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkekNDQVIyZ0F3SUJBZ0lSQUxGREYvNGZvbEZqSkJWdXhURkM0all3Q2dZSUtvWkl6ajBFQXdJd0d6RVoKTUJjR0ExVUVBeE1RY21Oc0xXMTBiSE10Y205dmRDMWpZVEFlRncweU5qQTNNVE14TmpNMk1qaGFGdzB5TmpFdwpNVEV4TmpNMk1qaGFNQnN4R1RBWEJnTlZCQU1URUhKamJDMXRkR3h6TFhKdmIzUXRZMkV3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFRR1FzeERMbXpCOFVaRUlDbGpuOXFJemxwZUxUMkx6WnQvVzdGUXBtdnQKczdzaEFMbTVYbnpkL0ljRzNqZm1iNUVxSGlOTnlNb3hzZ3ViRzlBS2VDdExvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVU5CVWNNNzdVVk9VZmRWYnVTZ1ptCmlqNkhFNmN3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUlnUHlEaHhzdGxmTk1VNGNKdFZROXdkSjFhTjdKTkQzN3EKY21ZTk1VMW0vQTRDSVFDU05vQzF1Z2VETmtwVFJIaW9lS3k2a0FNV3hJVktNbS9HcG9PRDloaGdJdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
