apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: robotics-content-lab-backend
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "robotics-content-lab-backend.novotny.live"
  labels:
    funnel: "false"
spec:
  externalDNS:
    enable: true
  host: robotics-content-lab-backend.novotny.live
  tls:
    secret: wildcard-tls
  upstreams:
  - name: robotics-content-lab-backend
    service: backend-service
    port: 8000
  routes:
  - path: =/
    action:
      redirect:
        url: /admin/
        code: 301
  - path: /
    action:
      pass: robotics-content-lab-backend