apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: robotics-content-lab-api
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "rcl-api.novotny.live"
  labels:
    funnel: "false"
spec:
  externalDNS:
    enable: true
  host: rcl-api.novotny.live
  tls:
    secret: wildcard-tls
    redirect:
      enable: true
  policies:
  - name: mtls-policy
  upstreams:
  - name: robotics-content-lab-api
    service: backend-service
    port: 8000
  routes:
  - path: =/media/resources
    action:
      return:
        code: 404
        type: text/plain
        body: Not found
  - path: /media/resources/
    action:
      return:
        code: 404
        type: text/plain
        body: Not found
  - path: /
    action:
      proxy:
        upstream: robotics-content-lab-api
        requestHeaders:
          pass: true
          set:
          - name: X-SSL-CLIENT-VERIFY
            value: ${ssl_client_verify}
          - name: X-SSL-CLIENT-S-DN
            value: ${ssl_client_s_dn}
