# external-secrets/es-dev-app.yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pihole-password
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-dev
    kind: ClusterSecretStore
  target:
    name: pihole-password
    deletionPolicy: Delete
  data:
    - secretKey: password
      remoteRef:
        conversionStrategy: Default	
        decodingStrategy: None
        metadataPolicy: None
        key: tools/pihole/pihole-password
        property: password
