apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: api-token
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-dev
    kind: ClusterSecretStore
  target:
    name: api-token
    deletionPolicy: Retain
  data:
    - secretKey: api-token
      remoteRef:
        conversionStrategy: Default	
        decodingStrategy: None
        metadataPolicy: None
        key: tools/cert-manager/api-token
        property: api-token
