apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps-apps
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/novo-lab/aoa.git
        revision: main
        directories:
          - path: apps/*
  template:
    metadata:
      name: "{{ base .path.basenameNormalized }}"
      labels:
        group: apps
    spec:
      project: default
      source:
        repoURL: https://github.com/novo-lab/aoa.git
        targetRevision: main
        path: "{{ .path.path }}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{ base .path.basenameNormalized }}"
      syncPolicy:
        automated: 
          enabled: true
        #   prune: true
        #   selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PrunePropagationPolicy=foreground
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true
