apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-postgres
spec:
  instances: 1

  storage:
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: nfs-client
      volumeMode: Filesystem

  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:16.9-0.4.3


  postgresql:
    shared_preload_libraries:
      - "vchord.so"
  
  

  bootstrap:
    initdb:
      database: immich-db
      owner: immich
      secret:
        name: immich-database-credentials
      postInitApplicationSQL:
        # Commands based on: https://immich.app/docs/administration/postgres-standalone/#without-superuser-permission
        - CREATE EXTENSION vchord CASCADE;
        - CREATE EXTENSION earthdistance CASCADE;
    

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: apps
                operator: Exists

    tolerations:
      - key: apps
        operator: Exists
        effect: NoSchedule
