name: Kustomize Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Kustomize
    steps:
      - uses: actions/checkout@v6


      - name: Run Kustomize Action
        uses: NovoG93/kustomize-action@main
        id: kustomize
        with:
          working-directory: "."
          changed-only: "false"
          fail-on-error: "true"
          output-dir: "manifests"
          ignore-dirs: "kind"
          